ratt-ru/CubiCal

cubical/DefaultParset.cfg, cubical/solver.py, cubical/tools/myoptparse.py, cubical/tools/parsets.py
=> fixes #62: adds option for uncorrected residuals

setup.py
=> Bumping version for release.

setup.py
This should cause vext to install correctly in a virtualenv.
=> Fixes #101.

setup.py
@JSKenyon please confirm -- is this the only place I need to change it?
=> fixes #111

cubical/data_handler.py
Added backstop for unfilled BITFLAG columns. Shouldn't really happen...
=> fixes #109, provisionally

cubical/DefaultParset.cfg, cubical/data_handler.py, cubical/flagging.py, cubical/machines/abstract_machine.py, cubical/machines/complex_2x2_machine.py, cubical/machines/complex_W_2x2_machine.py, cubical/machines/interval_gain_machine.py, cubical/machines/jones_chain_machine.py, cubical/machines/phase_diag_machine.py, cubical/machines/slope_machine.py, cubical/main.py, cubical/plots/ifrgains.py, cubical/solver.py, cubical/tools/parsets.py
A whole lotta fixes. #126 #127 #128 #129.
=> Fixes 126-129

cubical/data_handler.py
Fix to bad padding in prep_for_montblanc.
=> Emergency fix for montblanc prep routines.

setup.py
Added missing package to setup.py
=> Added database package to setup.py.

cubical/data_handler.py
Not really a bugfix -- just fiddled with the flag stats messages to make them a little bit more clear.
=> print better stats to clarify if #105 is still an issue

cubical/DefaultParset.cfg, cubical/data_handler.py, cubical/solver.py
@JSKenyon check it out. ``--sel-chan 1::1`` will get your WSRT data moving.
=> fixes #155

cubical/data_handler.py, cubical/database/casa_db_adaptor.py, cubical/machines/abstract_machine.py, cubical/main.py
Be less Stalinist about party declaration 229!
=> Fix issue #179

.gitignore, MANIFEST.in, docs/_static/theme_overrides.css, docs/conf.py, docs/index.rst, docs/installation.rst, docs/parset.rst, docs/usage.rst, setup.py
Ok - this is an attempt at keeping everyone happy.
You will now have to jump through a couple more hoops during the installation process. This should, however, make controlling cythonization simpler. Assuming you have have cloned the repo and have a working casacore, you must now do:
```
pip install cython numpy
python path/to/repo/setup.py gocythonize
pip install -e path/to/repo
```
You can add options to the pip installs (--user for those who eschew virtual environments). The explicit cythonization step also allows for forced recythonization via --force or -f:
```
python path/to/repo/setup.py gocythonize -f
```
Users are strongly encouraged to use the latest release which will be available via PyPI. Assuming you have a working casacore, you can simply:
```
pip install cubical
```
=> Update setup.py and MANIFEST.in

cubical/data_handler/ms_data_handler.py, cubical/solver.py, cubical/workers.py
Grrr trivial breakage... but going to need a point release....
=> Ooops I did it again

.gitattributes
https://github.com/ratt-ru/CubiCal/issues/185
=> dont export git attributes and ignore (#185)

cubical/data_handler/TiggerSourceProvider.py, cubical/data_handler/ms_tile.py
=> Custom spectral expressions for montblanc

cubical/DefaultParset.cfg, cubical/data_handler/DDFacetSim.py
This substantially improves the runtime in the initialization step for larger numbers of facets
=> Parallelize degridder initialization

cubical/solver.py
As it says on the label. Very tiny fix - see #359 for proof that it works.
=> Added a manual garbage collection step at the end of each solver call.

cubical/bin/plot-gain-solutions, cubical/data_handler/ms_tile.py, cubical/plots/gainsols.py, cubical/plots/leakages.py
=> Possible fixes for Python3 incompatibility.

cubical/data_handler/wisdom.py
=> Fix wisdom to assume n_dir is one in unusual cases.

cubical/machines/interval_gain_machine.py
@IanHeywood, @o-smirnov if you are both happy we can just merge this in.
=> Fix for #403.

cubical/machines/abstract_machine.py, cubical/machines/ifr_gain_machine.py
This should fix the circular import problem reported by @brianwelman2.
=> Move import statements to sidestep circular import.

docs/installation.rst
- Latest release version `1.6.1`
=> cubical installation from kern

cubical/plots/gainsols.py
`plot-gain-solutions` is currently broken. These changes should get it working again.
=> Minor fixes for plot-gain-solutions.
